spring.application.name=wedding-photo-box
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

#server.port=8080
#server.address=0.0.0.0

upload.directory=/home/cwhite56/Pictures/

# Per file limit
spring.servlet.multipart.max-file-size=25MB

# Total request limit — covers a reasonable batch
spring.servlet.multipart.max-request-size=100MB

aws.s3.bucket=amzn-s3-wedding-photo-box-2027
aws.region=us-east-2

spring.profiles.active=prod